# Generated by Django 2.0.1 on 2018-03-31 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1017', '0002_studentcourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=100, unique=True)),
                ('times', models.IntegerField()),
                ('accountType', models.IntegerField()),
                ('account', models.IntegerField()),
                ('address', models.CharField(max_length=42, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContractCourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=100, unique=True)),
                ('times', models.IntegerField()),
                ('cNo', models.IntegerField()),
                ('cName', models.CharField(max_length=40)),
                ('cCredit', models.IntegerField()),
                ('cNature', models.CharField(max_length=10)),
                ('cGrade', models.CharField(max_length=20)),
                ('cTerm', models.CharField(max_length=40)),
                ('cComposition', models.CharField(default='期末:100%', max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='ContractManagerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=100, unique=True)),
                ('times', models.IntegerField()),
                ('mNo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContractMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=100, unique=True)),
                ('times', models.IntegerField()),
                ('tNo', models.IntegerField()),
                ('cNo', models.IntegerField()),
                ('sNo', models.IntegerField()),
                ('mark', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContractSelectCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=100, unique=True)),
                ('times', models.IntegerField()),
                ('cNo', models.IntegerField()),
                ('sNo', models.IntegerField()),
                ('timestamp', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='ContractStudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=100, unique=True)),
                ('times', models.IntegerField()),
                ('sNo', models.IntegerField()),
                ('sName', models.CharField(max_length=40)),
                ('sClass', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ContractTeacherInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=100, unique=True)),
                ('times', models.IntegerField()),
                ('tNo', models.IntegerField()),
                ('tName', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='teachercourse',
            name='sClass',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
