# Generated by Django 2.0.1 on 2018-03-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab1017', '0003_auto_20180331_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractTeacherCourseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txid', models.CharField(max_length=100, unique=True)),
                ('times', models.IntegerField()),
                ('cNo', models.IntegerField()),
                ('tNo', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='contractcourseinfo',
            name='cComposition',
            field=models.CharField(max_length=5000),
        ),
    ]
